### PR TITLE
Minor Documentation tweaks

### PR DESCRIPTION
**Pull request by StevenACoffman**
Just noticed some lint.

### CODE REVIEW

**Comment by StevenACoffman** [comment]
@chrisgilbert I lightly tweaked the documentation, and then updated per your recent PR.

**Comment by wliao008** [comment]
👍  looks good to me, thanks @StevenACoffman!

**Comment by wliao008** [comment]
sorry clicked the wrong button

**Comment by chrisgilbert** [comment]
Thanks @StevenACoffman, we appreciate the contribution 😄

**Pull request merged**
